# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

#before_script: 
#  - apt -y install make autoconf libfftw3-dev libnetcdf-dev

stages:
  - build

build:
  stage: build
  script: make
  artifacts:
    paths:
      - rktest

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
