# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

before_script: 
  - apt update && apt -y install make autoconf libfftw3-dev libnetcdf-dev

rkest:
  script:
  - rktest -T 1

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
