# Running docker containers as:
#
# macOS running as x86: docker run --platform=linux/amd64 -it -v ${PWD}:/radarkit gcc
# macOS running as arm: docker run -it -v ${PWD}:/radarkit gcc
# linux running native: docker run -it -v ${PWD}:/radarkit gcc

stages:
  - build
  - test

variables:
  CC: "gcc"
  FAIL_STRING: "\e[38;5;214mFailed\e[m"
  PASS_STRING: "\e[38;5;46mAll tests passed\e[m"

before_script:
  - export TERM=xterm-256color
  - apt update && apt install -y bc libfftw3-dev libnetcdf-dev libssl-dev

build_linux:
  tags:
    - linux, x86_64
  stage: build
  image: gcc
  script:
    - git clone https://git.arrc.ou.edu/radar/radarkit.git
    - cd radarkit
    - git checkout ${CI_COMMIT_BRANCH}
    - make
  artifacts:
    expire_in: 1 week
    paths:
      - radarkit/libradarkit.a
      - radarkit/libradarkit.so
      - radarkit/rkutil

build_mac:
  tags:
    - macos, arm64
  stage: build
  image: gcc
  script:
    - git clone https://git.arrc.ou.edu/radar/radarkit.git
    - cd radarkit
    - git checkout ${CI_COMMIT_BRANCH}
    - make

basic:
  tags:
    - linux
  stage: test
  image: gcc
  needs:
    - build_linux
  script:
    - cd radarkit
    - ee=0
    - ./rkutil -T0; ee=$((ee+$?))
    - ./rkutil -T1; ee=$((ee+$?))
    - ./rkutil -T2; ee=$((ee+$?))
    - ./rkutil -T3; ee=$((ee+$?))
    - ./rkutil -T4; ee=$((ee+$?))
    - ./rkutil -T5; ee=$((ee+$?))
    - ./rkutil -T11; ee=$((ee+$?))
    - echo -n "" && [[ ${ee} == 0 ]] && echo ${PASS_STRING} || echo ${FAIL_STRING}
    - exit ${ee}

numeric:
  tags:
    - linux
  stage: test
  image: gcc
  needs:
    - build_linux
  script:
    - cd radarkit
    - ee=0
    - ./rkutil -T30; ee=$((ee+$?))
    - ./rkutil -T31; ee=$((ee+$?))
    - ./rkutil -T38; ee=$((ee+$?))
    - ./rkutil -T50; ee=$((ee+$?))
    - ./rkutil -T51; ee=$((ee+$?))
    - ./rkutil -T52; ee=$((ee+$?))
    - ./rkutil -T53; ee=$((ee+$?))
    - ./rkutil -T54; ee=$((ee+$?))
    - ./rkutil -T55; ee=$((ee+$?))
    - ./rkutil -T56; ee=$((ee+$?))
    - echo -n "" && [[ ${ee} == 0 ]] && echo ${PASS_STRING} || echo ${FAIL_STRING}
    - exit ${ee}

performance:
  tags:
    - linux
  stage: test
  image: gcc
  needs:
    - build_linux
  script:
    - cd radarkit
    - ee=0
    - ./rkutil -T60; ee=$((ee+$?))
    - ./rkutil -T61; ee=$((ee+$?))
    - ./rkutil -T62; ee=$((ee+$?))
    - ./rkutil -T63; ee=$((ee+$?))
    - echo -n "" && [[ ${ee} == 0 ]] && echo ${PASS_STRING} || echo ${FAIL_STRING}
    - exit ${ee}

# should_fail:
#   tags:
#     - linux
#   stage: test
#   image: gcc
#   needs:
#     - build_linux
#   script:
#     - cd radarkit
#     - exit 1
