stages:
  - build

variables:
  CC: "gcc"

before_script:
  - ln -sf /usr/share/zoneinfo/GMT /etc/localtime

build:
  tags:
    - linux
  stage: build
  image: gcc
  before_script:
    - apt update && apt install -y libfftw3-dev libnetcdf-dev libssl-dev
  script:
    - git clone https://git.arrc.ou.edu/radar/radarkit.git
    - cd radarkit
    - make
    - echo DONE
  artifacts:
    expire_in: 1 week
    paths:
      - radarkit/libradarkit.a
      - radarkit/rkutil
