stages:
  - build

variables:
  CC: "gcc"

before_script:
  - ln -sf /usr/share/zoneinfo/GMT /etc/localtime

build:
  stage: build
  image: ubuntu:20.04
    - apt update && apt install -y libfftw3-dev libnetcdf-dev libssl-dev
  tags:
    - linux
  script:
    - git clone https://git.arrc.ou.edu/radar/radarkit.git
    - cd radarkit
    - make
    - echo DONE
